### ISSUE TITLE
Link to 'Full Guide' is broken

### ISSUE THREAD

**Issue by benji1304** [SalesforceLabs/ActionPlansV4#20]
Link to the Full Guide from Appexchange page is broken

https://animated-train-661e89e5.pages.github.io/

<img width="324" alt="image" src="https://user-images.githubusercontent.com/7213889/159392246-b2d4b035-30a1-4fcf-9e74-3ddc185ddb14.png">

**Comment by dschach** [comment]
Thanks, @benji1304 - We are updating the AppExchange listing now. To see the guide, go to https://salesforcelabs.github.io/ActionPlansV4/

**Comment by tepp0f3l** [comment]
Corrected!!
