### ISSUE TITLE
Install Failure in PE Environment

### ISSUE THREAD

**Issue by forceDotMom** [SalesforceLabs/ActionPlansV4#28]
**Describe the bug**
Today I attempted to install the Managed AppExchange Package into a PE sandbox, and received multiple failure messages related to Apex Classes:

 Missing feature
Installing this package requires the following feature and its associated permissions: Apex Classes

**To Reproduce**
1. Navigate to Setup--> Home
2. Search for AppExchange
3. Click on AppExchange Marketplace in left sidebar
4. Search for "Action Plans"
5. Click on Action Plans V4
6. Click on Get it Now
7. Follow prompts to authenticate and choose environment
8. Eventually land on Installing Package status page
9. Wait for email notification that package has installed
10. Receive Install Failed message instead

**Expected behavior**
I expected the managed package to send me a nice "successfully installed" message. 

**Screenshots**
See attached PDF
[ActionPlans V4 Install Failure - Prfessional Edition.pdf](https://github.com/SalesforceLabs/ActionPlansV4/files/8525125/ActionPlans.V4.Install.Failure.-.Prfessional.Edition.pdf)

**Environment (please complete the following information):**
 Professional Edition Dev Sandbox

**Additional context**
nope.

**Comment by dschach** [comment]
Thanks @forceDotMom - this may be due to a security review flag that needs to be flipped. We will check with the AppExchange team to see why this isn't registering as able to be installed into the PE org.

**Comment by wtupyo** [comment]
This also happens exactly the same with the same missing feature error message on the Essentials edition (which the AppExchange page lists as a version supported for this app).

**Comment by forceDotMom** [comment]
I successfully installed this in the same Professional Edition sandbox this week. Yay!! However, there seems to be another bug preventing a template from being instantiated against any record. I’ll check the list of issues and see if it’s already logged and if not add it.

**Comment by forceDotMom** [comment]
Thanks David.
