### ISSUE TITLE
Too many query rows exception

### ISSUE THREAD

**Issue by marcin-zabadaj** [SalesforceLabs/ActionPlansV4#29]
**Describe the bug**
When I edit Action Plan, add a new Task, and save, the "LabsActionPlans: Too many query rows: 50001" exception is thrown.

**To Reproduce**
1. Go to Action Plan record
3. Click Edit
4. Add new Task and populate the required field
5. Click Save
6. See error

**Expected behavior**
Action Plan should be saved without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/91684099/164420922-a7649f7d-a123-42ab-9e69-c0bd3fceb55d.png)

**Log File**
[log.txt](https://github.com/SalesforceLabs/ActionPlansV4/files/8529500/log.txt)

**Additional Info**
I think the exception is thrown in ActionPlansBuilderUtilities class in the line 190: `for (Task tmpTask : [SELECT Id, TaskAPTask__c, Subject FROM Task WHERE TaskAPTask__c IN :mapAP.keySet()]) {`. When `mapAP` contains null as a key, the number of Tasks returned by query exceeds 50000, and the exception is thrown. You should update the `WHERE` part of your query to exclude Tasks with empty `TaskAPTask__c` field.

**Comment by dschach** [comment]
Thank you, @marcin-zabadaj - this will be updated in the next released version. We will change that map to a set that is populated after the upsert, so we are sure that only populated records are queried... but will still specify the value is not null, just in case. This is being done in branch release/4.2.0.

**Comment by dschach** [comment]
Please install 4.2.0 once it is live on Appexchange today/tomorrow and give feedback. Thank you!
