### ISSUE TITLE
ActionPlanCreateInvocable.makeActionPlanFromTemplate() won't create multiple Action Plans for the same record

### ISSUE THREAD

**Issue by sfdcmatt** [SalesforceLabs/ActionPlansV4#31]
We have 4 Action Plan Templates set up in our sandbox with "Criteria Change" in the name, and are trying to assign all 4 of them to a single custom object record. We're running the following script 

```
Map<Id,LabsActionPlans__ActionPlanTemplate__c> actionTemplates = new Map<ID, LabsActionPlans__ActionPlanTemplate__c>([SELECT ID, Name, LabsActionPlans__Description__c, LabsActionPlans__SkipWeekends__c,
LabsActionPlans__SkipDay__c FROM LabsActionPlans__ActionPlanTemplate__c WHERE Name like '%Criteria Change%']);

List<LabsActionPlans.ActionPlanCreateInvocable.CreateActionPlanRequest> requests = new List<LabsActionPlans.ActionPlanCreateInvocable.CreateActionPlanRequest>();

for(LabsActionPlans__ActionPlanTemplate__c ap: actionTemplates.values()) {
    LabsActionPlans.ActionPlanCreateInvocable.CreateActionPlanRequest req = new 
    LabsActionPlans.ActionPlanCreateInvocable.CreateActionPlanRequest();
    req.templateNameOrID = ap.Id;
    req.relatedRecordID = 'a1e7e000007j37gAAA';
    req.daysToActionPlanStart = 1;
    requests.add(req);
}
system.debug('requests : ' + requests);
List<Id> resultIDs = LabsActionPlans.ActionPlanCreateInvocable.makeActionPlanFromTemplate(requests);
system.debug('resultIDs : ' + resultIDs);
```

The first debug statement prints (formatted for readability, note templateNameOrID is unique in each of the 4 cases):
```
09:55:42:014 USER_DEBUG [14]|DEBUG|requests : (
CreateActionPlanRequest:[daysToActionPlanStart=1, relatedRecordID=a1e7e000007j37gAAA, templateNameOrID=a0I7e000009i8AhEAI], 
CreateActionPlanRequest:[daysToActionPlanStart=1, relatedRecordID=a1e7e000007j37gAAA, templateNameOrID=a0I7e000009i8AcEAI], 
CreateActionPlanRequest:[daysToActionPlanStart=1, relatedRecordID=a1e7e000007j37gAAA, templateNameOrID=a0I7e000009i8AwEAI], 
CreateActionPlanRequest:[daysToActionPlanStart=1, relatedRecordID=a1e7e000007j37gAAA, templateNameOrID=a0I7e000009i8ArEAI])
```

The second debug statement however prints (note the 4 identical Action Plan IDs:
```
09:58:22:798 USER_DEBUG [16]|DEBUG|resultIDs : (a0J7e000006bBRHEA2, a0J7e000006bBRHEA2, a0J7e000006bBRHEA2, a0J7e000006bBRHEA2)
```

Ultimately one 1 Action Plan is ever created on the target custom object record.

**Comment by dschach** [comment]
Thanks for the issue - what should it do? I'm happy for it to create one plan for every matching template if you think that's the way to go. Is that the desired outcome?
I'm also wondering about putting an active flag on the template. While that wouldn't help here, could it in the future?

**Comment by sfdcmatt** [comment]
Thanks! I'd expect this to work is to respect the key value pairs in the requests parameter to whatever was passed in. In this instance, we're asking to add 4 Action Plans to a single record. If we passed in key values pairs that had Record 1 and Record 2 mapped to 3 Action Plans (6 CreateActionPlanRequest records in total) I would expected 6 Action Plans to ultimately be created.
