### ISSUE TITLE
Lookup dropdown not populating (templates, opportunities, accounts, etc)

### ISSUE THREAD

**Issue by wtupyo** [SalesforceLabs/ActionPlansV4#33]
When using SF Lightning (professional) when creating templates unable to lookup and assign users to tasks.

<img width="493" alt="Screen Shot 2022-05-18 at 4 53 23 PM" src="https://user-images.githubusercontent.com/64756520/169181376-00c31497-b464-47af-87a2-f836bb3f089d.png">

When trying to assign an action plan template to an account/opportunity/anywhere unable to search for templates to add.

<img width="770" alt="Screen Shot 2022-05-18 at 4 53 03 PM" src="https://user-images.githubusercontent.com/64756520/169181430-5154283d-925f-4b92-ba79-a1cc9079a8b2.png">

The workaround I found is to switch to SF Classic in order to apply any action plan templates to opportunities/actions/etc or to be able to assign users to tasks in an action plan template.

Using: 
Mac OS 12.4
Salesforce Professional

Browsers tested:
Safari 15.5 (17613.2.7.1.8)
Google Chrome 101.0.4951.64

**Comment by dschach** [comment]
This looks like it's a JavaScript issue. I'll add it to the next release, once I've reproduced it. Thank you.

**Comment by dschach** [comment]
@wtupyo Can you please try doing this again, but this time with the Chrome console open, and can you copy/paste any messages from there?

**Comment by wtupyo** [comment]
I don't normally use Chrome (not at my laptop the that has it) but here's the javascript log from Safari that shows up when typing into the lookup field for adding an action plan to an opportunity. If you still need from Chrome, I can grab that computer instead.

`[Error] Failed to load resource: the server responded with a status of 500 (Server Error) (54.0, line 0)
[Error] {faultcode:'sf:API_DISABLED_FOR_ORG', faultstring:'API_DISABLED_FOR_ORG: API is not enabled for this Organization or Partner', detail:{UnexpectedErrorFault:{exceptionCode:'API_DISABLED_FOR_ORG', exceptionMessage:'API is not enabled for this Organization or Partner', }, }, }
	(anonymous function) (connection.js:1015)
	(anonymous function) (connection.js:1824)
	(anonymous function) (connection.js:1763)
	(anonymous function) (connection.js:1413)
	searchRecords (ActionPlanCreation:169)
	onkeyup (ActionPlanCreation:132)
[Error] Failed to load resource: the server responded with a status of 500 (Server Error) (54.0, line 0)
[Error] {faultcode:'sf:API_DISABLED_FOR_ORG', faultstring:'API_DISABLED_FOR_ORG: API is not enabled for this Organization or Partner', detail:{UnexpectedErrorFault:{exceptionCode:'API_DISABLED_FOR_ORG', exceptionMessage:'API is not enabled for this Organization or Partner', }, }, }
	(anonymous function) (connection.js:1015)
	(anonymous function) (connection.js:1824)
	(anonymous function) (connection.js:1763)
	(anonymous function) (connection.js:1413)
	searchRecords (ActionPlanCreation:169)
	onkeyup (ActionPlanCreation:132)
[Error] Failed to load resource: the server responded with a status of 500 (Server Error) (54.0, line 0)
[Error] {faultcode:'sf:API_DISABLED_FOR_ORG', faultstring:'API_DISABLED_FOR_ORG: API is not enabled for this Organization or Partner', detail:{UnexpectedErrorFault:{exceptionCode:'API_DISABLED_FOR_ORG', exceptionMessage:'API is not enabled for this Organization or Partner', }, }, }
	(anonymous function) (connection.js:1015)
	(anonymous function) (connection.js:1824)
	(anonymous function) (connection.js:1763)
	(anonymous function) (connection.js:1413)
	searchRecords (ActionPlanCreation:169)
	onkeyup (ActionPlanCreation:132)
[Error] Failed to load resource: the server responded with a status of 500 (Server Error) (54.0, line 0)
[Error] {faultcode:'sf:API_DISABLED_FOR_ORG', faultstring:'API_DISABLED_FOR_ORG: API is not enabled for this Organization or Partner', detail:{UnexpectedErrorFault:{exceptionCode:'API_DISABLED_FOR_ORG', exceptionMessage:'API is not enabled for this Organization or Partner', }, }, }
	(anonymous function) (connection.js:1015)
	(anonymous function) (connection.js:1824)
	(anonymous function) (connection.js:1763)
	(anonymous function) (connection.js:1413)
	searchRecords (ActionPlanCreation:169)
	onkeyup (ActionPlanCreation:132)
[Error] Failed to load resource: the server responded with a status of 500 (Server Error) (54.0, line 0)
[Error] {faultcode:'sf:API_DISABLED_FOR_ORG', faultstring:'API_DISABLED_FOR_ORG: API is not enabled for this Organization or Partner', detail:{UnexpectedErrorFault:{exceptionCode:'API_DISABLED_FOR_ORG', exceptionMessage:'API is not enabled for this Organization or Partner', }, }, }
	(anonymous function) (connection.js:1015)
	(anonymous function) (connection.js:1824)
	(anonymous function) (connection.js:1763)
	(anonymous function) (connection.js:1413)
	searchRecords (ActionPlanCreation:169)
	onkeyup (ActionPlanCreation:132)`

**Comment by dschach** [comment]
Oh, then it's good news. Please make sure you have version 4.2.0 at a minimum. That's the version that was certified for professional edition orgs. Just install the latest version on top of what you have and it will be fine.

**Comment by wtupyo** [comment]
That is the version that is installed; I actually had installed it ran into the issue so uninstalled, reinstalled and it persisted. 

¯\_(ツ)_/¯

**Comment by JoseVillarreal-CXC** [comment]
![image](https://user-images.githubusercontent.com/111294926/191863027-48579ea2-d7e6-4390-8108-0294de3d031a.png)

@dschach I'm having the same issue, the dropdown doesn't show up. The user can assign tasks fine on the standard task tab. Using Chrome 105 on Windows 10, the console log shows:

```
VM20418:1          POST https://cxc--admin--labsactionplans.sandbox.vf.force.com/services/Soap/u/54.0 500 (Server Error)
(anonymous) @ VM20418:1
send @ connection.js:595
sforce.SoapTransport.send @ connection.js:1013
sforce.Connection._invoke @ connection.js:1824
sforce.Connection.invoke @ connection.js:1763
sforce.Connection.query @ connection.js:1413
searchRecords @ actionplancreation?refId=0031X00000tZvBgQAK&refType=Contact&retURL=%2F003%2Fo&sfdcIFrameOrigin=https://cxc--admin.sandbox.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&nonce=42bc321422883502ce46a92521bd00908bfa8ab095dab57f7b52775a906964d5&ltn_app_id=06m3X000000VUxXQAW&clc=0:287
onkeyup @ actionplancreation?refId=0031X00000tZvBgQAK&refType=Contact&retURL=%2F003%2Fo&sfdcIFrameOrigin=https://cxc--admin.sandbox.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&nonce=42bc321422883502ce46a92521bd00908bfa8ab095dab57f7b52775a906964d5&ltn_app_id=06m3X000000VUxXQAW&clc=0:247
connection.js:1015 Uncaught sforce.Xml {faultcode: 'sf:INVALID_FIELD', faultstring: "INVALID_FIELD: \n'%j%' AND IsActive = true AND Prof…L or the describe call for the appropriate names.", detail: s…e.Xml}
sforce.SoapTransport.send @ connection.js:1015
sforce.Connection._invoke @ connection.js:1824
sforce.Connection.invoke @ connection.js:1763
sforce.Connection.query @ connection.js:1413
searchRecords @ actionplancreation?refId=0031X00000tZvBgQAK&refType=Contact&retURL=%2F003%2Fo&sfdcIFrameOrigin=https://cxc--admin.sandbox.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&nonce=42bc321422883502ce46a92521bd00908bfa8ab095dab57f7b52775a906964d5&ltn_app_id=06m3X000000VUxXQAW&clc=0:287
onkeyup @ actionplancreation?refId=0031X00000tZvBgQAK&refType=Contact&retURL=%2F003%2Fo&sfdcIFrameOrigin=https://cxc--admin.sandbox.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&nonce=42bc321422883502ce46a92521bd00908bfa8ab095dab57f7b52775a906964d5&ltn_app_id=06m3X000000VUxXQAW&clc=0:247
```
