### ISSUE TITLE
Documentation Update:  Custom Object instructions missing namespace prefix in code snippets

### ISSUE THREAD

**Issue by tschug** [SalesforceLabs/ActionPlansV4#35]
- [x] 1. Under the section **To Start Using an Object with Action Plans** the following code snippet for the the custom object trigger
```
ActionPlansTriggerHandlers.actionPlansSObjectTriggerHandler( 'Custom_Object__c' )
```
is missing the namespace reference and should be updated to
```
LabsActionPlans.ActionPlansTriggerHandlers.actionPlansSObjectTriggerHandler( 'Custom_Object__c' )
```

- [x] 2. Under the section **Adding a New Custom Object Action Plan button to the Action Plan object** the following code snippet for the button URL 
```
{!URLFOR( $Action.ActionPlan__c.New, null, [refType="CustomObject__c", refId=CustomObject__c.Id])}
```
is also missing the namespace prefix and should be updated to
```
{!URLFOR( $Action.LabsActionPlans__ActionPlan__c.New, null, [refType="CustomObject__c", refId=CustomObject__c.Id])}
```

**Comment by dschach** [comment]
Thank you.
