### ISSUE TITLE
Task assignment email not triggered

### ISSUE THREAD

**Issue by Xshaoyi** [SalesforceLabs/ActionPlansV4#39]
**Describe the bug**
Task assignment email not triggered.

**To Reproduce**
Login as userA
1. Go to 'case related list action plan'
2. Click on 'create case action plan'
3. Create an action plan and add a task to userB, make sure send email is checked.
4. No task assignment email was triggered to userB

**Expected behavior**
task assignment email was triggered to userB

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ Windows]
 - Browser [chrome,]
 - Action Plans Version [4.2]

**Additional context**
UserA manualy create task and assigned to UserB, a task assigment email is triggered.

**Comment by dschach** [comment]
The code only sends an email for tasks that aren't dependent on other tasks, but I don't remember why. I will update the package to send an email for every task where the checkbox is checked.
