### ISSUE TITLE
Assign APTasks to Queues

### ISSUE THREAD

**Issue by dschach** [SalesforceLabs/ActionPlansV4#42]
**Is your feature request related to a problem? Please describe.**
I cannot assign APTasks to Queues

**Describe the solution you'd like**
Allow assignment of Tasks to Queues when the parent record is owned by a queue, or allow APTasks to be assigned to queues.
- Update the lookup to include queues, probably filtering for that related object type. Include error handling if the queue is not allowed for tasks and the parent object. This may need a text field for APTask ownerId, though this would make reporting quite difficult. Using APTask.OwnerId is not an option due to the Master-Detail relationship.
- I would rather not clear the User field if the Task is owned by a Queue, as that may confuse reporting, but here, reporting is inaccurate, so this is a significant lift.

**Describe alternatives you've considered**
Assigning the APTask to some user and then using Flow on Task to reassign to the parent record owner. (This would require a text field on ActionPlan for the OwnerId of the parent record. How do we handle this when the parent owner changes?)

**Additional context**
There are a lot of considerations for this, so it is low-priority. For now, updating the Task OwnerId using Flow or a trigger may be the best option, but those values may be overwritten if the APTask is edited. 

For now, we have blocked the APTask owner from updating to a queue, and the record will keep the existing value. The hope is that this will not create a loop that will overwrite the Task if the User field is still a User when the Task owner is a Queue.

**Comment by dschach** [comment]
Partially fixed in release 4.3.0, which will be put on AppExchange shortly. Still curious about how to have a field that holds a user or a queue, as I REALLY don't want to put too much logic in the VF page or controller. If anything, I'd like to move all logic to a central worker class.

**Comment by emcobb** [comment]
@dschach Do you know when ver 4.3 will be on AppExchange? Thanks

**Comment by dschach** [comment]
Great question. I've been locked out of the repo because I'm not a
Salesforce employee. Currently trying to get access.
