### ISSUE TITLE
Feature Request: Order object

### ISSUE THREAD

**Issue by aKasperavicius** [SalesforceLabs/ActionPlansV4#46]
**Description:** 
Ability to assign an action plan to an **Order** object type.

**Rationale:** 
Because the Order object typically relates to _delivering_ whatever was sold, an action plan on an Order (e.g. after execution of a contract) could help with the multiple steps that exist even in very basic scenarios (e.g. following up on delivery, billing, etc.).

While this could be seen as overlapping into Service cloud, because the Order object does exist in Sales cloud (and I've seen it used often), having an action plan for Orders in this version would be tremendous.

Your very cool work-around for dealing with multiple-Whats would be stretched, but I'd argue that the order object, over any other, deserves it—if technically possible.

![OrderExample](https://user-images.githubusercontent.com/6973841/179251986-686c5dad-cecd-444a-9e7e-1a9eb1c56490.png)

**Comment by dschach** [comment]
Thanks @aKasperavicius . I have a question: Should we display the related Order as `Order.OrderNumber`:`Order.Name`?

**Comment by aKasperavicius** [comment]
Right, orders have some unique features. OrderNumber is alway present, Name is editable and **blank is allowed** by default. Typical use case is where multiple orders/deliveries are made against a single contract and the name is the PO or Contract number with a suffix. In standard reports and elsewhere, Salesforce shows clickable blank Order name fields as just "-". Would that work or too confusing?

**Comment by dschach** [comment]
In progress. I don't think it will be feasible in the first attempt to include Order Name. OrderNumber is accessible to all users with Order access. I'll release with just the number, like Contract, and will assess security gotchas for Name in another release.

**Comment by dschach** [comment]
Oh, just saw that Name is more important than Number. Okay, I will find a way to work with security/FLS before the next release.

**Comment by aKasperavicius** [comment]
After reviewing this more, I think it should probably just be number—especially if easiest to implement.

This is because in Lighting **records** the default is number, and hovering displays name. 

In most cases (e.g. on the tasks themselves) users will be working with standard lookup fields, so matching that standard behavior as closely as possible is probably the target.

Also, pulling the name in some contexts could be easily done using custom formula fields, reports, etc, by an admin on an as needed basis, so order name display issues could even be considered beyond scope. 

Sorry for the run around, I should probably have thought this through more before responding earlier.

**Comment by dschach** [comment]
Covered in #47 and will create new package version asap.

**Comment by dschach** [comment]
I have to revert this change. The order object is one that can be selectively turned on and off in an org, and installing this package would force an org to turn it on, so I can't do that.

**Comment by dschach** [comment]
Having said that, it might be nice to have a package extension for Order one day; that's not on the near-term roadmap.
