### ISSUE TITLE
TaskAPTask Field - Lookup deletion prevention

### ISSUE THREAD

**Issue by aKasperavicius** [SalesforceLabs/ActionPlansV4#48]
**Is your feature request related to a problem? Please describe.**
Because action plans create tasks, those tasks become orphaned (from the action plan) if the action plan is subsequently deleted. This can cause a confusing lack of context, or worse multiple instances of the same task if an enthusiastic user creates, deletes, and recreates action plans against the same records. 

**Describe the solution you'd like**
Change "_What to do if the lookup record is deleted?_" option for the **TaskAPTask** field on **Task** object to be user selectable. An admin could then prevent action plans from being deleted prior to the user cleaning up any created tasks. 

**Describe alternatives you've considered**
A manual installation of the package would likely allow the change, but this would seem to be a standard need.

**Additional context**
### Currently the option is completely disabled on the field:

<img width="578" alt="Currently restricted" src="https://user-images.githubusercontent.com/6973841/180363210-7a5ad282-ac62-4d2e-9cff-23ea797b0ad6.png">

### As an admin, would prefer to have the standard option to prevent deletion of lookup:

<img width="578" alt="Standard option" src="https://user-images.githubusercontent.com/6973841/180362663-a742ca3d-f9ad-49f5-8002-a61c83973a82.png">

**Comment by dschach** [comment]
This is a limitation from Salesforce that this cannot be allowed to be user-selectable, as that affects field level security. You could make this happen with a trigger on Task that checks for the type of object in WhatId and doesn't allow that field to be cleared once it is filled (though I'd recommend that only be applied to open Tasks, as you may want to clear out old Action Plans eventually).

**Comment by aKasperavicius** [comment]
> This is a limitation from Salesforce that this cannot be allowed to be user-selectable, as that affects field level security. You could make this happen with a trigger on Task that checks for the type of object in WhatId and doesn't allow that field to be cleared once it is filled (though I'd recommend that only be applied to open Tasks, as you may want to clear out old Action Plans eventually).

Good to know. Note: A "no code" solution could be achieved with record triggered flow doing the same check.

**Comment by aKasperavicius** [comment]
> as you may want to clear out old Action Plans eventually

Not sure if this is worth a feature request, but perhaps an "**isActive**" boolean field on action plan might be another way to handle retired plans—rather than planning to delete them?

Because, similar to old products used in opportunities, campaigns, etc. - once an action plan has created tasks, the context of creation could be useful for later reporting/reconstruction of events in a business process review or audit.

Anyway, don't wanna go down that rabbit hole, just a passing thought.
