### ISSUE TITLE
Unable to Reassign Task to Queue

### ISSUE THREAD

**Issue by ebradley54** [SalesforceLabs/ActionPlansV4#51]
**Describe the bug**
The documentation suggests that after a Task has been created via the package, it can then be reassigned to a Queue "any other way you'd like...". I have tried to do this via the UI, via API, and via the packages invocable Apex class with a Flow, all of which is generating the same Error message:

LabsActionPlans.APTask: execution of AfterUpdate caused by: System.DmlException: Upsert failed. First exception on row 0 with id a461x0000009hmDAAQ; first error: FIELD_INTEGRITY_EXCEPTION, Assigned To: id value of incorrect type: 00G1x00000Aqu2PEAR: [LabsActionPlans__User__c] (LabsActionPlans)

Could be something silly that I am doing or not doing, just hoping to have some feedback if you expect this to work or not.

**To Reproduce**
1. Create an Action Plan Template with Template Tasks
2. Create a Case, and then a new Action Plan using the AP Template
3. Tasks are successfully added to the Case, assigned to the users identified in the Template Tasks.
4. View one of the new Tasks, and change the Assigned To user to a Queue.
5. On Save, the error is generated preventing save.
6. Attempt to update the OwnerId on Task via API, get the same error.
7. Attempt to generate the Action Plan and update the new Tasks via Flow and invocable Apex action, get the same error.
8. If removing the Task relationship to AP Task, then the OwnerId can be changed to a Queue, but if reestablishing the relationship with AP Task will get the same error.

**Expected behavior**
Should be able to reassign the standard Task manually to a Queue via UI, API, or declarative automation such as Flow.

**Screenshots**
![image](https://user-images.githubusercontent.com/47434482/184256536-8ecfa4be-f822-44b3-ba06-f62a9f3fd0d1.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Action Plans Version: 4.2.1
 - Salesforce UI: Lightning Experience
 - Org Edition: Unlimited

**Comment by mfschafer** [comment]
I just put Action Plans V4 into a sandbox for a client yesterday and am encountering this same issue when trying to reassign to queues. Is there something I need to do to allow this?
