### ISSUE TITLE
OwnerId field not found

### ISSUE THREAD

**Issue by wdci-dev** [SalesforceLabs/ActionPlansV4#52]
**Describe the bug**
When using the action plan on a child object (with master-detail relationship which doesn't have OwnerId), the action plan failed with the error OwnerId field not found.

**To Reproduce**
1. Enabled Unassigned Task Defaults to Record Owner
2. Create a new object MyObject__c
3. Create a master detail lookup field on the object, target can be any existing salesforce object e.g., Account
4. Setup the action plan template and action template task for the new object MyObject__c
5. Create a flow that invoke the action plan creation (https://github.com/SalesforceLabs/ActionPlansV4#flow)
6. Create an object action that calls the flow
7. Create a new MyObject__c record and use the object action to create the action plan

**Expected behavior**
The action plan task should be created and assigned to parent owner

**Screenshots**
na

**Environment (please complete the following information):**
 - OS: [e.g. OSX, Windows]
 Windows

chrome
 
 - Action Plans Version (e.g. 4.0.1) (See Setup > Installed Packages)
4

 - Salesforce UI
Lightning and classic
 
 - Org Edition
Enterprise

**Additional context**
na

**Comment by dschach** [comment]
That is an interesting feature request. It would be easier to assign tasks to the running user, as there could be multiple levels of parents, and we can't even know the relationship name for the child to parent object.

**Comment by wdci-dev** [comment]
@dschach it is true that there could be multiple levels of parents. Instead of handling the complexity of figuring out the parent, maybe you could consider to add a field on the action task template object to allow us to define the owner id field API name? By default it will be OwnerId. Then we could create any custom field custom field (e.g., formula) to provide the right owner id.

**Comment by dschach** [comment]
For now, the next released version will assign those tasks to the running user. You may wish to have a Flow or trigger that will reassign tasks for those children to the owner of the parent record.
