### ISSUE TITLE
Action Plans Creator permissions don't have access to edit AP Template field

### ISSUE THREAD

**Issue by JoseVillarreal-CXC** [SalesforceLabs/ActionPlansV4#54]
**Describe the bug**
Action Plans Creator permission set > Field permissions for LabsActionPlans__ActionPlan__c.LabsActionPlans__Action_Plan_Template__c are set to read only. When user with the Action Plans Creator permission set create an action plan, they should be able to select an Action Plan Template to create it from. Currently that field is not accessible.

**To Reproduce**
1. Go to Action Plans Related List
2. Click on the button to create AP form template
3. Scroll down to the first field to select a template
4. See error the field is not an active combo box, rather only white space

**Expected behavior**
The Creator user should be able to select the Action Plan Template, just like user with the Action Plans Admin can

**Screenshots**

![Action Plans Creator](https://user-images.githubusercontent.com/111294926/186277265-23a20341-62c2-4303-931b-65a07b882c29.png)
![Action Plans Admin](https://user-images.githubusercontent.com/111294926/186277269-f4566191-5b28-4e66-9869-699613138626.png)

**Environment (please complete the following information):**
 - OS: [e.g. OSX, Windows]
 
 
 - Action Plans Version (e.g. 4.0.1) (See Setup > Installed Packages)

 - Salesforce UI
 - [ ] Classic
 - [x] Lightning Experience
 
 - Org Edition
 - [ ] Personal
 - [ ] Contact Manager
 - [ ] Professional
 - [x] Enterprise
 - [ ] Unlimited
 - [ ] Developer

**Additional context**

**Comment by dschach** [comment]
I am unable to reproduce this error. I gave a user access only to Account View All and the Action Plans Creator permission set, and the field rendered.
The Visualforce says that the field will be rendered if the user can edit the field.
Have you updated to the latest version?

**Comment by JoseVillarreal-CXC** [comment]
I just installed it again in a fresh sandbox today and the issue persists. I believe that it has to do with the Action Plan Template field not being editable on the Action Plan object... I cloned the Action Plan Creator permission set and marked it for edit, and now the dropdown box shows up as it should while creating an action plan. Could this field have edit access on the Action Plan Creator permission set, please?

![image](https://user-images.githubusercontent.com/111294926/191828426-bfaf3801-da2e-4640-8e8a-8897c6309fc6.png)

**Comment by dschach** [comment]
Thank you. I'll look into it more.
Due to some security hoops I need to jump through, we're on hold for
development for a week or so. But I'll keep you posted here as I make
changes locally.



Sent via mobile. Please excuse brevity.
