### ISSUE TITLE
New Opportunity Action Plan - Not Loading Templates

### ISSUE THREAD

**Issue by RHornbeckKG** [SalesforceLabs/ActionPlansV4#92]
**Describe the bug**
When I go to add an opportunity action plan, none of the templates show up in the search to select from.  I have made the templates public and have ensured admin permission set.  However, if you enter the first part of template name and hit the enter button in the template search, it selects the template name but does not fill the action plan with the template information.

**To Reproduce**
1. Go to opportunity
2. Click Create Opportunity Action Plan from Action Plan related list
3. Try to enter/search for an existing action plan template
4. No results appear

**Expected behavior**
To see the all action plan templates to choose from.

**Screenshots**
1. Entering a search term in the template search field: 
![Screenshot_20230104_060647](https://user-images.githubusercontent.com/121986877/210673192-6c3245a3-738f-4180-9812-d805905ea011.png)
url)

2. Hitting enter on the search term:
![Screenshot_20230104_060711](https://user-images.githubusercontent.com/121986877/210673314-640ed778-879f-49de-a258-a7ebe0ccd4c3.png)

**Environment (please complete the following information):**
 - Windows 11 Pro 
 - Chrome 108.0.5359.125
 - Action Plans v4.2.1
 - Salesforce Lightning
 - Enterprise Edition

**Comment by adepew** [comment]
Just went through something similar myself. Can you check whether the users's profile has "API Enabled"? This is what fixed it for me.

**Comment by RHornbeckKG** [comment]
> Just went through something similar myself. Can you check whether the users's profile has "API Enabled"? This is what fixed it for me.

@adepew I just checked and the subject profiles (including mine as Admin) are API enabled.

**Comment by RHornbeckKG** [comment]
@dschach any possibility this is going to get looked into?  I realize it a labs application, but tomorrow will be 1 month since reporting this issue.
